/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{report_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis Job */
        post: operations["create_analysis_job_v1_reports__report_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisJobCreate */
        AnalysisJobCreate: {
            /** @default hosted_baseline */
            engine_mode: components["schemas"]["EngineMode"];
        };
        /** AnalysisJobCreated */
        AnalysisJobCreated: {
            /** Job Id */
            job_id: string;
            /** Replayed */
            replayed: boolean;
            status: components["schemas"]["AnalysisJobStatus"];
        };
        /**
         * AnalysisJobStatus
         * @enum {string}
         */
        AnalysisJobStatus: "queued" | "running" | "completed" | "failed";
        /** AnalysisResult */
        AnalysisResult: {
            /** Abstain Reasons */
            abstain_reasons: string[];
            /** Barriers */
            barriers: components["schemas"]["Barrier"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Missing Information */
            missing_information: string[];
            /** Model Score */
            model_score: number | null;
            /** Precursors */
            precursors: components["schemas"]["Precursor"][];
            provenance: components["schemas"]["Provenance"];
            /** References */
            references: components["schemas"]["ReferenceCitation"][];
            /** Relevant Rule Ids */
            relevant_rule_ids: components["schemas"]["RuleId"][];
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "pending" | "reviewed";
            /** Rule Scores */
            rule_scores: {
                [key: string]: number | null;
            } | null;
            rules_assessment: components["schemas"]["RulesAssessment"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            score_kind: components["schemas"]["ScoreKind"];
            sif_label: components["schemas"]["SifLabel"];
            /** Summary */
            summary: string;
            /** Unassessed Rule Ids */
            unassessed_rule_ids: components["schemas"]["RuleId"][];
        };
        /** AuxiliaryModel */
        AuxiliaryModel: {
            /** Model Id */
            model_id: string;
            /** Provider */
            provider: string;
            /** Purpose */
            purpose: string;
            /** Revision */
            revision: string;
        };
        /** Barrier */
        Barrier: {
            /** Evidence Ids */
            evidence_ids: string[];
            state: components["schemas"]["BarrierState"];
            /** Tag */
            tag: string;
        };
        /**
         * BarrierState
         * @enum {string}
         */
        BarrierState: "failed" | "missing" | "present" | "unknown";
        /** CapabilitiesLimits */
        CapabilitiesLimits: {
            /** Max Active Jobs */
            max_active_jobs: number;
            /** Max Api Body Bytes */
            max_api_body_bytes: number;
            /** Narrative Max Codepoints */
            narrative_max_codepoints: number;
            /** Narrative Min Codepoints */
            narrative_min_codepoints: number;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Canonical Rule Ids */
            canonical_rule_ids: components["schemas"]["RuleId"][];
            /** Current Model Display Name */
            current_model_display_name: string;
            /** Engines */
            engines: components["schemas"]["EngineCapability"][];
            limits: components["schemas"]["CapabilitiesLimits"];
            /**
             * Rubric Version
             * @constant
             */
            rubric_version: "sif-pilot-v1";
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
        };
        /** EngineCapability */
        EngineCapability: {
            /** Available */
            available: boolean;
            /** Display Name */
            display_name: string;
            engine_mode: components["schemas"]["EngineMode"];
            /** Live Inference */
            live_inference: boolean;
        };
        /**
         * EngineMode
         * @enum {string}
         */
        EngineMode: "hosted_baseline" | "encoder" | "qwen_adapter" | "recorded_sample";
        /** Evidence */
        Evidence: {
            /**
             * Field
             * @enum {string}
             */
            field: "narrative" | "activity";
            /** Id */
            id: string;
            method: components["schemas"]["EvidenceMethod"];
            /**
             * Occurrence
             * @default 0
             */
            occurrence: number;
            /** Quote */
            quote: string;
        };
        /**
         * EvidenceMethod
         * @enum {string}
         */
        EvidenceMethod: "llm_extracted" | "rule_matched" | "reviewer";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Analysis Id */
            analysis_id: string | null;
            /** Attempt Count */
            attempt_count: number;
            /** Error Code */
            error_code: string | null;
            /** Job Id */
            job_id: string;
            /** Report Id */
            report_id: string;
            status: components["schemas"]["AnalysisJobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LiveStatus */
        LiveStatus: {
            /** Status */
            status: string;
        };
        /** ModelBarrier */
        ModelBarrier: {
            /** Evidence Quote */
            evidence_quote: string;
            state: components["schemas"]["BarrierState"];
            /** Tag */
            tag: string;
        };
        /** ModelOutputSubset */
        ModelOutputSubset: {
            /** Barriers */
            barriers: components["schemas"]["ModelBarrier"][];
            /** Evidence Quotes */
            evidence_quotes: string[];
            /** Missing Information */
            missing_information: string[];
            /** Precursors */
            precursors: components["schemas"]["ModelPrecursor"][];
            /** Reference Passage Ids */
            reference_passage_ids: string[];
            /** Relevant Rule Ids */
            relevant_rule_ids: components["schemas"]["RuleId"][];
            rules_assessment: components["schemas"]["RulesAssessment"];
            sif_label: components["schemas"]["SifLabel"];
            /** Summary */
            summary: string;
            /** Unassessed Rule Ids */
            unassessed_rule_ids: components["schemas"]["RuleId"][];
        };
        /** ModelPrecursor */
        ModelPrecursor: {
            /** Evidence Quote */
            evidence_quote: string;
            /** Tag */
            tag: string;
        };
        /** Precursor */
        Precursor: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Tag */
            tag: string;
        };
        /** Provenance */
        Provenance: {
            /** Auxiliary Models */
            auxiliary_models: components["schemas"]["AuxiliaryModel"][];
            engine_mode: components["schemas"]["EngineMode"];
            /** Inference Is Live */
            inference_is_live: boolean;
            /**
             * Label Guide Version
             * @constant
             */
            label_guide_version: "sif-pilot-v1";
            /** Model Id */
            model_id: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Prompt Version
             * @constant
             */
            prompt_version: "sif-analysis-v1";
        };
        /** ReadyStatus */
        ReadyStatus: {
            /** Dependencies */
            dependencies: {
                [key: string]: string;
            };
            /** Status */
            status: string;
        };
        /** ReferenceCitation */
        ReferenceCitation: {
            /** Passage Id */
            passage_id: string;
            /** Source Id */
            source_id: string;
        };
        /** ReportCreate */
        ReportCreate: {
            /**
             * Activity
             * @default null
             */
            activity: string | null;
            /**
             * Is Synthetic
             * @default false
             */
            is_synthetic: boolean;
            /** Narrative */
            narrative: string;
            /**
             * Report Date
             * @default null
             */
            report_date: string | null;
            /**
             * Site
             * @default null
             */
            site: string | null;
        };
        /** ReportCreated */
        ReportCreated: {
            /** Replayed */
            replayed: boolean;
            /** Report Id */
            report_id: string;
            /** Version */
            version: number;
        };
        /** ReportDetail */
        ReportDetail: {
            /** Analyses */
            analyses: components["schemas"]["StoredAnalysis"][];
            report: components["schemas"]["ReportRecord"];
        };
        /** ReportRecord */
        ReportRecord: {
            /** Activity */
            activity: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Narrative */
            narrative: string;
            /** Report Date */
            report_date: string | null;
            /** Report Group Id */
            report_group_id: string;
            /** Site */
            site: string | null;
            /** Version */
            version: number;
        };
        /**
         * RuleId
         * @enum {string}
         */
        RuleId: "bypassing_safety_controls" | "confined_space" | "driving" | "energy_isolation" | "hot_work" | "line_of_fire" | "safe_mechanical_lifting" | "work_authorisation" | "working_at_height";
        /**
         * RulesAssessment
         * @enum {string}
         */
        RulesAssessment: "complete" | "partial" | "unknown";
        /**
         * ScoreKind
         * @enum {string}
         */
        ScoreKind: "none" | "uncalibrated_model_score" | "calibrated_score";
        /**
         * SifLabel
         * @enum {string}
         */
        SifLabel: "yes" | "no" | "unknown";
        /** StoredAnalysis */
        StoredAnalysis: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            result: components["schemas"]["AnalysisResult"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStatus"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
        };
    };
    capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_v1_reports_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_job_v1_reports__report_id__analyses_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
